### ISSUE TITLE
Add tutorial to run the cbg_executor example

### ISSUE THREAD

**Issue by carlossvg** [ros-realtime/community#23]
There is one real-time related demo in ros2/examples. It would be useful to create a tutorial explaining how to run the demo and showing some results in a real-time system (i.e. RPI4 with PREEMPT-RT).

Instructions already exists in [cbg_executor](https://github.com/ros2/examples/tree/master/rclcpp/executors/cbg_executor) so maybe this tutorial is not necessary. At least I think it would be useful to create a tutorial document and link the demo readme to make this demo more visible. 

More information:
- https://roscon.ros.org/2018/presentations/ROSCon2018_Lightning1_4.pdf
- https://vimeo.com/292707644
- https://micro.ros.org/docs/concepts/client_library/execution_management/#callback-group-level-executor

**Comment by carlossvg** [comment]
Hi @ralph-lange, I created this issue as a proposal to improve the RTWG documentation. Could you provide some feedback on whether this makes sense to you?

**Comment by ralph-lange** [comment]
Hi @carlossvg, I'm happy to contribute such a tutorial, including measurement results from a sample hardware platform. Did you have a RTWG website/documentation in mind or the Tutorials section of https://docs.ros.org/, i.e. https://docs.ros.org/en/galactic/Tutorials.html? Currently, the demo is listed on this website in the Features section only.

**Comment by carlossvg** [comment]
@ralph-lange My idea was to create a tutorial in https://real-time-working-group.readthedocs.io/en/latest/index.html and add it to the tutorial section (not created yet). The rationale is to collect all the real-time related resources in one place. If you prefer to have a tutorial in the ROS2 docs I would just add an entry in the RTWG docs and link the external tutorial so it's visible from there too.

Also, I will be happy to support with the tutorial reproducing the results in additional hardware platforms.

**Comment by ralph-lange** [comment]
I'll make a PR for the ROS 2 docs and will share the link with you as soon as it is accepted. But it will take me a few days to make this PR.

**Comment by carlossvg** [comment]
Great, thanks!

**Comment by carlossvg** [comment]
This will be done as part of this issue: https://github.com/ros-realtime/community/issues/32
