### ISSUE TITLE
Add tutorial to run a  Autoware-based reference system demo application

### ISSUE THREAD

**Issue by carlossvg** [ros-realtime/community#24]
As part of the ROScon 2021 executor workshop it has been discuss the possibility to use a Autoware-based reference system for the hands-on session. 

As part of this effort, and even if the demo is not finally included in the hands-on session, it would be interesting to create a tutorial explaining how to run a Autoware-based reference application and achieving  deterministic execution.

- https://github.com/ros-realtime/reference-system

## Acceptance Criteria
- [ ]  A tutorial exists explaining how to use ROS 2 tracing to instrument and debug a real-time application

**Comment by carlossvg** [comment]
Hi @Karsten1987, I created this issue to discuss if it's possible to create a tutorial for a ros2_control application focusing on real-time execution. We could use this tutorial as a reference for the ROScon 2021 hands-on session or just as an interesting document for ROS 2 users interested in real-time and ros-control. 

I'm not aware of ongoing work in the ros-control working group so I don't know how well this is aligned with your roadmap. Please tell me if this proposal makes sense to you or whether you had a different idea in mind.

**Comment by JanStaschulat** [comment]
@carlossvg Thanks for organizing the different hands-on-tuturials. Yesterday, I had a chat with Karsten, and we will contribute to the hands-on-session with a ros-control application. Our main idea is to demonstrate the tooling which could be used to develop a real-time application with ROS 2 that execute with a high frequency (1kHz) (e.g. ROS tracing tools, finding bugs and resolve them that lead to to high jitter etc.). 

Could we have a zoom-meeting to discuss in more detail the scope of the individual contributions?

**Comment by carlossvg** [comment]
@JanStaschulat Sounds good. I'll write an e-mail to schedule the meeting. 

FYI @razr @LanderU

**Comment by christophebedard** [comment]
@carlossvg I'm guessing we can remove the mention of ros2_control from this issue (1st acceptance criterion) since we're using an Autoware-based reference system instead?

**Comment by carlossvg** [comment]
The tutorial was created here: https://github.com/ros-realtime/reference-system/blob/main/autoware_reference_system/README.md
