### ISSUE TITLE
Provide support for ROS 2 on  QNX

### ISSUE THREAD

**Issue by dejanpan** [ros-realtime/community#5]
1. Blackberry has a support in progress: https://github.com/asobhy-qnx/ros2
2. Apex.AI has tons of internal tools and infrastructure 

## Acceptance Criteria
1. [x] cross compilation instructions exist
3. [x] Merge instructions in ros2 documentation => This will be done once QNX is a Tier 3 platform. In the meanwhile, the documentation will leave here: https://ros2-qnx-documentation.readthedocs.io/
3. [x] decide if it should become T1, T2 or T3: https://www.ros.org/reps/rep-2000.html#support-tiers => Tier 3 platform

**Comment by JanStaschulat** [comment]
@dejanpan The above link  https://github.com/asobhy-qnx/ros2 does not exist any more. What is the current status of Blackberry support of ROS 2 on QNX?

**Comment by LanderU** [comment]
@JanStaschulat, looks like the author removed the repo. The progress was tracked at https://github.com/ros2/ros2/issues/988

cc @dejanpan

**Comment by carlossvg** [comment]
Here is the link to the temporary documentation: https://github.com/asobhy-qnx/ros2_documentation/blob/master/source/Installation/Rolling/QNX-Development-Setup.rst

This link will be replaced once the article is validated and merged in ROS 2 documentation.

**Comment by JanStaschulat** [comment]
@carlossvg thanks a lot.

**Comment by carlossvg** [comment]
The official ROS2 QNX Documentation
 is now hosted in: https://ros2-qnx-documentation.readthedocs.io/
