### ISSUE TITLE
Carry out performance test measurements for ROS 2 stack

### ISSUE THREAD

**Issue by dejanpan** [ros-realtime/community#7]
This is to implement a SW system for performance testing and to carry out & report the measurements. 

An ideal system is described here: https://drive.google.com/file/d/15nX80RK6aS8abZvQAOnMNUEgh7px9V5S/view.

Example reports:
1. https://discourse.ros.org/t/ros-2-real-time-working-group-online-meeting-18-may-26-2020-meeting-minutes/14302/19?u=dejan_pangercic
1. Lots of roscon talks
1. OR buildfarm

## Acceptance Criteria
TBD

**Comment by dejanpan** [comment]
Depends on https://github.com/ros-realtime/community/issues/3

**Comment by flynneva** [comment]
Sort of related to this topic is [the new `performance_report` package](https://gitlab.com/ApexAI/performance_test/-/tree/apex-os-performance-reporter) that helps automate test runs as well as generating reports from the logs of `performance_test`. Still not yet merged into every branch of `performance_test` but a really good baseline so far.

**Comment by carlossvg** [comment]
@flynneva Thanks for the info. I will use that branch to run some tests and complete the performance test tutorial https://github.com/ros-realtime/rtwg_documentation/pull/30

**Comment by carlossvg** [comment]
Completed in https://ros-realtime.github.io/ros2_realtime_benchmarks/
